name: Unity Test and Build (Best)

on:
  workflow_dispatch: {}

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache Library
      uses: actions/cache@v2
      with:
        path: Library
        key: Library-${{ hashFiles('**/Library') }}

    - name: Build Unity Project
      uses: game-ci/unity-builder@v4.0.1
      env:
        UNITY_SERIAL: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: Unity/
        unityVersion: '2022.2.21f1' # Replace with your Unity version (2022.3.13f1, 2022.3.1f1 fails)
        targetPlatform: 'StandaloneWindows64' # Replace with your desired build platform
        buildMethod: BuildScript.PerformBuild
    # Optional: Use this step to upload artifacts (builds and test results)
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build/ # Replace with your build output directory

